server:
  port: 8081
spring:
  application:
    name: backend
  web:
    resources:
      encoding:
        charset: UTF-8
  security:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5455/energy_monitoring
    username: user
    password: root
    driver-class-name: org.postgresql.Driver

  logging:
    level:
      org:
        thymeleaf: DEBUG
        springframework:
          web: DEBUG
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

  telegram:
    bot:
      name: energy_monitoring_1akBot
      token: 7556649009:AAFfD--f-fLcjIE29GNWM9b7jUrkL0z-neQ
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  report:
    server:
      base-url: http://localhost:8081